version: "3.8"

services:
  backend:
    build: ./backend
    container_name: vaukonverter-backend
    ports:
      - "5050:5000"
    environment:
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    networks:
      - vaukonverter-network

  frontend:
    build: ./front
    container_name: vaukonverter-frontend
    ports:
      - "3050:80"
    depends_on:
      - backend
    networks:
      - vaukonverter-network

  worker:
    build: ./worker
    container_name: vaukonverter-worker
    ports:
      - "8050:8000"
    networks:
      - vaukonverter-network

networks:
  vaukonverter-network:
    driver: bridge
