apiVersion: apps/v1
kind: Deployment
metadata:
  name: vau-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vau-frontend
  template:
    metadata:
      labels:
        app: vau-frontend
    spec:
      containers:
        - name: frontend
          image: viderncic/vaukonverter-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vau-frontend
spec:
  selector:
    app: vau-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
