apiVersion: v1
kind: Secret
metadata:
  name: r2-secrets
type: Opaque
stringData:
  R2_ACCOUNT_ID: "REPLACE_ME"
  R2_ACCESS_KEY_ID: "REPLACE_ME"
  R2_SECRET_ACCESS_KEY: "REPLACE_ME"
  R2_BUCKET_NAME: "REPLACE_ME"
