name: CD - Dry Run Deploy

on:
  push:
    branches:
      - cd-test
  workflow_dispatch:

jobs:
  dry-run-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_MARTA }}
          key: |
            ${{ secrets.SERVER_SSH_KEY_MARTA }}
          port: 22
          debug: true
          script: |
            echo "SSH connection successful"
            whoami
            hostname
