name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build and Push"]
    types:
      - completed
    branches:
      - port/Test

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_VID }}
          key: ${{ secrets.SERVER_SSH_KEY_VID }}
          port: 22
          script: |
            echo "SSH connection successful!"
            echo "Updating Docker images..."
            docker pull vidernecic/vaukonverter-frontend:latest
            docker pull vidernecic/vaukonverter-backend:latest
            docker pull vidernecic/vaukonverter-worker:latest
            echo "Restarting containers..."
            docker stop vau_front || true
            docker rm vau_front || true
            docker run -d --name vau_front -p 3000:3000 vidernecic/vaukonverter-frontend:latest
            docker stop vau_backend || true
            docker rm vau_backend || true
            docker run -d --name vau_backend -p 8000:8000 vidernecic/vaukonverter-backend:latest
            docker stop vau_worker || true
            docker rm vau_worker || true
            docker run -d --name vau_worker vidernecic/vaukonverter-worker:latest
            echo "Deploy finished successfully!"
