name: CD - Deploy via SSH

on:
  push:
    branches:
      - cd-test  # workflow se pokreće kad push-aš na svoj test branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # ovo je cloud runner, ne self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_MARTA }}
          key: |
            ${{ secrets.SERVER_SSH_KEY_MARTA }}
          port: 22
          debug: true
          script: |
            echo "SSH connection successful!"
            echo "Updating Docker images from Docker Hub..."
            docker pull vidernecic/vaukonverter-frontend:latest
            docker pull vidernecic/vaukonverter-worker:latest
            docker pull vidernecic/vaukonverter-backend:latest
            echo "Restarting containers..."
            docker stop vau_front || true
            docker rm vau_front || true
            docker run -d --name vau_front vidernecic/vaukonverter-frontend:latest
            docker stop vau_worker || true
            docker rm vau_worker || true
            docker run -d --name vau_worker vidernecic/vaukonverter-worker:latest
            docker stop vau_backend || true
            docker rm vau_backend || true
            docker run -d --name vau_backend vidernecic/vaukonverter-backend:latest
            echo "Deploy finished successfully!"
