name: CD - Dry Run Deploy

# workflow se pokreÄ‡e samo na cd-test branch
on:
  push:
    branches: [ cd-test ]
  pull_request:
    branches: [ cd-test ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test SSH connection
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER_MARTA }}
    key: |
      ${{ secrets.SERVER_SSH_KEY_MARTA }}
    port: 22
    debug: true
    script: |
      echo "SSH connection successful"
      whoami
      hostname

